### ISSUE TITLE
RomParser::loadBuffer() should put sanity check on ROM size

### ISSUE THREAD

**Issue by thompGIT** [josephstill/chip-8#9]
/disassembler/RomParser.cpp(40)

`loadBuffer()` pulls in a user controlled file of unrestrained size.

**Comment by josephstill** [comment]
I added a check to the MainWindow that ensures selection of an empty or non existent ROM. The command line will allow attempting to disassemble or hex dump an invalid file. In this case, there will be an error displayed.
